# Generated by Django 5.2.7 on 2025-11-03 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_teachercourseselection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizattendance',
            name='month',
            field=models.PositiveIntegerField(default=11),
        ),
        migrations.AlterField(
            model_name='teachercourseselection',
            name='semester',
            field=models.CharField(choices=[('Spring24-25', 'Spring 24-25'), ('Summer24-25', 'Summer 24-25'), ('Fall24-25', 'Fall 24-25'), ('Spring25-26', 'Spring 25-26'), ('Summer25-26', 'Summer 25-26'), ('Fall25-26', 'Fall 25-26')], max_length=20),
        ),
    ]
