# Generated by Django 5.2.7 on 2025-10-09 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_course_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_type', models.CharField(choices=[('mcq', 'MCQ'), ('scenario-mcq', 'Scenario MCQ'), ('code', 'Code'), ('theory', 'Theory')], max_length=20)),
                ('question_text', models.TextField()),
                ('options', models.JSONField(blank=True, null=True)),
                ('answer', models.CharField(blank=True, max_length=100, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.course')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.topic')),
            ],
        ),
    ]
