# Generated by Django 5.2.7 on 2025-10-09 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_marks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marks',
            old_name='created_at',
            new_name='uploaded_at',
        ),
        migrations.AlterUniqueTogether(
            name='marks',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='marks',
            name='updated_at',
        ),
    ]
