# Generated by Django 5.2.7 on 2025-10-27 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_quizattendance'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='quizattendance',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='quizattendance',
            name='month',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterUniqueTogether(
            name='quizattendance',
            unique_together={('student', 'course', 'week', 'month')},
        ),
    ]
