# Generated by Django 5.2.7 on 2025-10-27 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_quizattendance_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattendance',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
