# Generated by Django 5.2.7 on 2025-11-07 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_section_studentinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
