# Generated by Django 5.2.7 on 2025-11-07 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_marks_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks',
            name='section',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='marks',
            name='semester',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
