# Generated by Django 5.2.7 on 2025-12-14 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_teachersyllabusupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizattendance',
            name='month',
            field=models.PositiveIntegerField(default=12),
        ),
        migrations.CreateModel(
            name='AIQuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_marks', models.FloatField(default=0)),
                ('max_marks', models.FloatField(default=0)),
                ('attempt_date', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_quiz_attempts', to='accounts.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_quiz_attempts', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_quiz_attempts', to='accounts.topic')),
            ],
            options={
                'ordering': ['-attempt_date'],
            },
        ),
    ]
