# Generated by Django 5.2.7 on 2025-12-14 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_quizattendance_month_aiquizattempt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aiquizattempt',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='aiquizattempt',
            old_name='attempt_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='aiquizattempt',
            old_name='max_marks',
            new_name='max_score',
        ),
        migrations.RenameField(
            model_name='aiquizattempt',
            old_name='total_marks',
            new_name='score',
        ),
        migrations.RemoveField(
            model_name='aiquizattempt',
            name='topic',
        ),
        migrations.AddField(
            model_name='aiquizattempt',
            name='topic_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='aiquizattempt',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.course'),
        ),
        migrations.AlterField(
            model_name='aiquizattempt',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
