# Generated by Django 6.0.5 on 2026-05-13 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_aiquizattempt_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizattendance',
            name='month',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
